import React, { useEffect, useState } from 'react';
import { StudioSheet } from './social.jsx';
import { styleImageBlob } from './model.js';
const { Icon }=window;
const localLink=['localhost','127.0.0.1','[::1]'].includes(location.hostname);
export default function ShareSheet({look,onSave,onClose,onVote}) {
 const [saved,setSaved]=useState({...look,privacy:look.privacy||'public'}),[file,setFile]=useState(null),[preview,setPreview]=useState(''),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{let active=true,previewUrl;styleImageBlob(look).then(blob=>{if(active){previewUrl=URL.createObjectURL(blob);setPreview(previewUrl);setFile(new File([blob],`${(look.title||'RealCloset').replace(/[\\/:*?"<>|]/g,'').slice(0,60)}.png`,{type:'image/png'}));}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setReady(true);});return()=>{active=false;if(previewUrl)URL.revokeObjectURL(previewUrl);};},[look]);
 const urlFor=post=>post.sample?`${location.origin}/?screen=feed&post=${encodeURIComponent(post.id)}`:post.share?`${location.origin}/?style=${encodeURIComponent(post.share)}`:'';
 const canSendFile=!!file&&typeof navigator.share==='function'&&typeof navigator.canShare==='function'&&navigator.canShare({files:[file]});
 const download=()=>{if(!file)return;const url=URL.createObjectURL(file),a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);};
 const copy=async()=>{setBusy(true);setError('');setMessage('');try{const next=urlFor(saved)?saved:onSave?await onSave({...saved,privacy:saved.privacy==='public'?'public':'link'}):null;if(!next||!urlFor(next))throw new Error('이 게시물의 공유 링크를 찾지 못했어요.');setSaved(next);await navigator.clipboard.writeText(urlFor(next));setMessage(localLink?'로컬 링크를 복사했어요. 다른 기기에서는 열 수 없어요.':'링크를 복사했어요.');}catch(e){setError(e.message);}finally{setBusy(false);}};
 const visibility=async privacy=>{setBusy(true);setError('');try{setSaved(await onSave({...saved,privacy}));setMessage('공개 범위를 변경했어요.');}catch(e){setError(e.message);}finally{setBusy(false);}};
 const send=async()=>{setError('');setMessage('');if(canSendFile){setBusy(true);try{await navigator.share({files:[file],title:saved.title,text:`${saved.author||'나'}의 RealCloset 스타일`});}catch(e){if(e.name!=='AbortError')setError('공유창을 열지 못했어요. 이미지를 저장해 보내 주세요.');}finally{setBusy(false);}return;}if(localLink){if(file){download();setMessage('이미지를 저장했어요. 원하는 앱에 첨부해 보내 주세요.');}else setError('이미지를 준비하지 못했어요. 링크 복사를 이용해 주세요.');return;}if(navigator.share&&urlFor(saved)){try{await navigator.share({title:saved.title,url:urlFor(saved)});}catch(e){if(e.name!=='AbortError')setError('공유창을 열지 못했어요. 링크 복사를 이용해 주세요.');}}else await copy();};
 return <StudioSheet open title="공유하기" desktopMaxW={460} zIndex={155} dismissOnScrim onClose={onClose}><section className="rc-feed-share" role="dialog" aria-label="피드 공유"><div className="rc-share-preview"><div className="rc-share-thumb">{preview&&<img src={preview} alt={`${look.title} 공유 이미지`}/>}</div><div><strong>{look.author||'나'}</strong><p>{look.title}</p><small>{file?'착장 이미지로 공유할 수 있어요.':ready?'이미지를 준비하지 못했어요.':'공유할 이미지를 준비하는 중…'}</small></div></div><div className="rc-share-destinations"><button disabled={busy||!ready} onClick={send}><span><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d="M12 16V3m-4 4 4-4 4 4M5 12v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2v-7"/></svg></span><b>다른 앱으로</b><small>{canSendFile?'공유 앱 선택':'이미지로 보내기'}</small></button><button disabled={busy} onClick={copy}><span><Icon name="link" size={24}/></span><b>링크 복사</b><small>{localLink?'로컬 링크':'게시물 링크'}</small></button><button disabled={busy||!file} onClick={()=>{download();setMessage('이미지를 저장했어요.');}}><span><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3v12m-4-4 4 4 4-4M5 16v4h14v-4"/></svg></span><b>이미지 저장</b><small>PNG 파일</small></button></div>{error&&<p className="rc-error" role="alert">{error}</p>}{message&&<p className="rc-share-status" role="status">{message}</p>}{onSave&&<section className="rc-share-visibility" aria-label="공개 범위"><h3>공개 범위</h3><div className="rc-share-options">{Object.entries({private:'나만 보기',link:'링크 받은 사람',public:'피드에 공개'}).map(([value,label])=><button key={value} disabled={busy} aria-pressed={saved.privacy===value} onClick={()=>visibility(value)}>{label}</button>)}</div></section>}{onVote&&<button className="rc-friend-vote" onClick={onVote}><span>친구에게 코디 투표</span><span aria-hidden="true">→</span></button>}</section></StudioSheet>;
}
