import React,{useEffect,useState} from 'react';
import {createPortal} from 'react-dom';
import {api,SAMPLE_LOOKS} from './model.js';
import {StyleCanvas} from './collage-canvas.jsx';
import CreatorProfile from './creator-profile.jsx';
import './social.css';
const {Icon,BottomSheet,EmptyState}=window;
export function StudioSheet({children,title,description,centered:_centered,bodyStyle,...props}){return createPortal(<BottomSheet {...props}><div className="lb-sheet-body rc-studio-sheet" style={{padding:'10px 24px 26px',maxHeight:'80dvh',overflowY:'auto',...bodyStyle}}>{title&&<div className="rc-sheet-heading"><header className="rc-dialog-head"><h2>{title}</h2><button aria-label={`${title} 닫기`} onClick={props.onClose}><Icon name="x" size={20}/></button></header>{description&&<p className="rc-sheet-description">{description}</p>}</div>}{children}</div></BottomSheet>,document.body);}
export const socialChanged=()=>window.dispatchEvent(new Event('rc-social-update'));
export const identity=prefs=>({author:prefs?.nickname||prefs?.name||prefs?.email?.split('@')[0]||'나',avatar:''});
export function RestyleIcon({size=24}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d="M13 5H5a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8"/><path d="m16 3 5 5M10 14l-1 4 4-1L22 8a2.12 2.12 0 0 0-3-3Z"/></svg>;}
export function useSocialProfile(prefs){
 const [data,setData]=useState(null),[error,setError]=useState('');
 const {author}=identity(prefs);
 useEffect(()=>{let alive=true;const load=()=>api('/social').then(x=>{if(alive){setData(x);setError('');}}).catch(e=>{if(alive)setError(e.message);});api('/profile',{method:'PUT',body:JSON.stringify({author})}).then(load).catch(e=>{if(alive)setError(e.message);});window.addEventListener('rc-social-update',load);window.addEventListener('focus',load);const timer=setInterval(load,30000);return()=>{alive=false;clearInterval(timer);window.removeEventListener('focus',load);window.removeEventListener('rc-social-update',load);};},[author]);
 return {data,error};
}
const personInfo=person=>person.sample?{...person,avatar:SAMPLE_LOOKS.find(x=>x.author===person.author)?.avatar}:person;
export function SocialStats({ctx,onPeople}){
 const {data,error}=useSocialProfile(ctx.prefs),[view,setView]=useState(null);
 const counts=[['게시글',data?.looks.length||0],['팔로잉',data?.followingPeople.length||0],['팔로워',data?.followerPeople.length||0]];
 return <><div className="rc-social-stats" aria-label="내 활동">{counts.map(([label,count])=><button key={label} aria-label={`${label} ${count}개 목록 보기`} onClick={()=>label==='게시글'?setView(label):onPeople(label)}><b>{data?count:'—'}</b><span>{label}</span></button>)}</div>{view&&<StudioSheet open centered desktopMaxW={620} zIndex={130} onClose={()=>setView(null)}><section className="rc-social-list" role="dialog" aria-label="게시글 목록"><header className="rc-dialog-head"><h2>게시글</h2><button aria-label="활동 목록 닫기" onClick={()=>setView(null)}><Icon name="x" size={20}/></button></header>{error&&<p className="rc-error">{error}</p>}{data?.looks.length?<div className="rc-social-posts">{data.looks.map(look=><a key={look.id} href={`/?style=${look.share}`} target="_blank" rel="noreferrer"><StyleCanvas look={look} showCredits={false}/><span>{look.title}</span></a>)}</div>:<p className="rc-creator-empty">피드에 공개한 스타일이 여기에 모여요.</p>}</section></StudioSheet>}</>;
}
export function ConnectionsPage({ctx,initialTab,onClose}){
 const {data,error}=useSocialProfile(ctx.prefs),[tab,setTab]=useState(initialTab),[query,setQuery]=useState(''),[limit,setLimit]=useState(50),[profile,setProfile]=useState(null),[busy,setBusy]=useState(null),[actionError,setActionError]=useState('');
 const people=(tab==='팔로워'?data?.followerPeople:data?.followingPeople)||[];
 const filtered=people.filter(p=>p.author.toLowerCase().includes(query.trim().toLowerCase()));
 const following=new Set((data?.followingPeople||[]).map(p=>p.creatorId));
 const unfollow=async person=>{setBusy(person.creatorId);setActionError('');try{const state=await api('/state');await api('/state',{method:'PUT',body:JSON.stringify({...state,follows:state.follows.filter(id=>id!==person.creatorId)})});socialChanged();}catch(e){setActionError(e.message);}finally{setBusy(null);}};
 return <div className="rc-connections-page"><header className="rc-page-head"><div className="rc-feed-heading"><button className="rc-feed-head-icon" aria-label="마이페이지로 돌아가기" onClick={onClose}><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="m14 5-7 7 7 7"/></svg></button><h1>팔로워 · 팔로잉</h1></div></header><section className="rc-social-page"><div className="rc-tabs" role="tablist" aria-label="팔로워·팔로잉">{['팔로워','팔로잉'].map(name=><button key={name} id={`rc-people-tab-${name}`} role="tab" aria-selected={tab===name} aria-controls="rc-people-panel" className={tab===name?'on':''} onClick={()=>{setTab(name);setQuery('');setLimit(50);}}>{name} {data?(name==='팔로워'?data.followerPeople.length:data.followingPeople.length):''}</button>)}</div><div id="rc-people-panel" role="tabpanel" aria-labelledby={`rc-people-tab-${tab}`}><label className="rc-people-search"><Icon name="search" size={18}/><input type="search" aria-label={`${tab} 검색`} placeholder={`${tab} 검색`} value={query} onChange={e=>{setQuery(e.target.value);setLimit(50);}}/></label>{(error||actionError)&&<p className="rc-error" role="alert">{error||actionError}</p>}{!data&&!error?<p className="rc-muted" role="status">목록을 불러오는 중…</p>:filtered.length?<><div className="rc-social-people">{filtered.slice(0,limit).map(p=>{const person=personInfo(p);return <div className="rc-following-row" key={p.creatorId}><button aria-label={`${p.author} 프로필 보기`} onClick={()=>setProfile(person)}><span className="rc-post-avatar">{person.avatar?<img src={person.avatar} alt=""/>:<Icon name="user" size={20}/>}</span><span>{p.author}</span></button>{following.has(p.creatorId)&&<button className="rc-following-toggle" aria-label={`${p.author} 언팔로우`} disabled={busy===p.creatorId} onClick={()=>unfollow(p)}>팔로잉</button>}</div>;})}</div>{filtered.length>limit&&<button className="rc-social-more" onClick={()=>setLimit(n=>n+50)}>더 보기</button>}</>:!error&&<div className="rc-connections-empty"><EmptyState icon={query?'search':'users'} title={query?'검색 결과가 없어요':tab==='팔로워'?'아직 팔로워가 없어요':'아직 팔로우한 사람이 없어요'} wide={window.innerWidth>=760} padTop={false} hintHidden>{query?'다른 이름으로 검색해 보세요.':tab==='팔로워'?'내 스타일을 공유해 보세요.':'피드에서 취향이 맞는 사람을 찾아보세요.'}</EmptyState></div>}</div></section>{profile&&<StudioSheet open centered desktopMaxW={780} zIndex={140} onClose={()=>setProfile(null)}><CreatorProfile person={profile} onClose={()=>setProfile(null)} onOpen={look=>{location.href=look.sample?`/?screen=feed&post=${look.id}`:`/?style=${look.share}`;}} onSaveItem={async item=>{const state=await api('/state');await api('/state',{method:'PUT',body:JSON.stringify({...state,collections:[{id:crypto.randomUUID(),type:'item',item},...state.collections]})});}}/></StudioSheet>}</div>;
}
window.RCConnectionsPage=ConnectionsPage;
export function NotificationMenu({onNavigate}){
 const [unread,setUnread]=useState(0);
 useEffect(()=>{let active=true;const load=()=>api('/notifications?limit=1').then(x=>{if(active)setUnread(x.unread);}).catch(()=>{});load();const timer=setInterval(load,30000);window.addEventListener('rc-social-update',load);window.addEventListener('focus',load);return()=>{active=false;clearInterval(timer);window.removeEventListener('rc-social-update',load);window.removeEventListener('focus',load);};},[]);
 return <button className="rc-feed-head-icon rc-notification-bell" aria-label={`알림${unread?` · 읽지 않은 알림 ${unread}개`:''}`} title="알림" onClick={onNavigate}><svg width="23" height="23" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></svg>{unread>0&&<span className="rc-notification-dot"/>}</button>;
}
export function NotificationPage({onOpen,onProfile}){
 const [notifications,setNotifications]=useState([]),[hasMore,setHasMore]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=async offset=>{setBusy(true);setError('');try{const next=await api(`/notifications?offset=${offset}&limit=30`);setNotifications(xs=>offset?[...xs,...next.notifications]:next.notifications);setHasMore(next.hasMore);const ids=next.notifications.filter(x=>!x.read).map(x=>x.id);if(ids.length){await api('/notifications/read',{method:'POST',body:JSON.stringify({ids})});socialChanged();}}catch(e){setError(e.message);}finally{setBusy(false);}};
 useEffect(()=>{load(0);},[]);
 return <section className={`rc-social-page rc-notifications${!notifications.length&&!busy&&!error?' is-empty':''}`} aria-label="알림 목록">{error&&<p className="rc-error" role="alert">{error}</p>}{notifications.length>0&&<div className="rc-notification-list"><h2>최근 알림</h2><ul>{notifications.map(x=><li key={x.id}><button className="rc-notification-row" onClick={()=>{if(x.look)onOpen(x.look);else onProfile(x.actor);}}><span className="rc-post-avatar">{x.actor.avatar?<img src={x.actor.avatar} alt=""/>:<Icon name="user" size={20}/>}</span><span className="rc-notification-copy"><span><b>{x.actor.author}</b>{x.kind==='restyle'?'님이 내 스타일을 리스타일했어요.':x.kind==='follow'?'님이 나를 팔로우했어요.':'님이 내 스타일을 좋아해요.'}</span><small><time dateTime={x.createdAt}>{new Date(x.createdAt).toLocaleDateString('ko-KR',{month:'short',day:'numeric'})}</time>{x.look?' · 스타일 보기':' · 프로필 보기'}</small></span>{x.look&&<span className="rc-notification-art"><StyleCanvas look={x.look} showCredits={false}/></span>}</button></li>)}</ul></div>}{!notifications.length&&!busy&&!error&&<EmptyState icon="bell" title="아직 알림이 없어요" wide={window.innerWidth>=760} hintHidden>좋아요, 팔로우, 리스타일 소식을<br/>여기서 확인할 수 있어요.</EmptyState>}{busy&&<p className="rc-notification-status" role="status">알림을 불러오는 중…</p>}{(hasMore||error)&&<button className="rc-social-more" disabled={busy} onClick={()=>load(notifications.length)}>{error?'다시 불러오기':'더 보기'}</button>}</section>;
}
export function ClosetVisibility({value=true,onChange}){return <div className="rc-closet-visibility"><div><b>옷 공개</b><span>공개한 옷은 프로필에서 볼 수 있어요.</span></div><div role="group" aria-label="옷 공개 범위"><button type="button" aria-pressed={value} onClick={()=>onChange(true)}>공개</button><button type="button" aria-pressed={!value} onClick={()=>onChange(false)}>나만 보기</button></div></div>;}
window.RCSocialStats=SocialStats;
window.RCClosetVisibility=ClosetVisibility;
window.RC_SYNC_CLOSET_ITEMS=async(items,prefs)=>{await Promise.all(items.map(item=>api(`/closet/${encodeURIComponent(item.id)}`,{method:'PUT',body:JSON.stringify({item,public:item.public===true})})));if(prefs)await api('/profile',{method:'PUT',body:JSON.stringify({author:identity(prefs).author})});socialChanged();};
