import React, { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { BACKGROUNDS, SAMPLE_ITEMS, arrange, exportImage, writeDraft, clearDraft } from './model.js';
import { CUTOUTS } from './sticker-catalog.js';
import { GIPHY_PICKS } from './giphy-catalog.js';
import { OPENMOJI } from './openmoji-catalog.js';
import { EMOJI_PACKS, INKS, id, normalizeLayers, importFile } from './collage.js';
import { StyleCanvas } from './collage-canvas.jsx';
import './story-editor.css';
import {StudioSheet} from './social.jsx';
import { readImageHistory, rememberImages } from './image-history.js';
const { Btn, Icon, BottomSheet }=window;
const TOOLS=['스티커','펜','텍스트','이미지','GIF','옷장','배경'];
const thumb=x=>({id:x.id,name:x.name,category:x.category,img:x.img||'',brand:x.brand||'',price:x.price||'',color:x.color||'',size:x.size||'',material:x.material||'',store:x.store||'',note:x.note||'',url:x.url||'',kind:'owned'});
function Options({ values, value, onChange }) {return <div className="rc-lab-options">{values.map(x=><button key={x} className={value===x?'on':''} aria-pressed={value===x} onClick={()=>onChange(x)}>{x}</button>)}</div>;}
function Swatches({value,onChange}) {return <div className="rc-lab-swatches">{INKS.map(x=><button key={x} style={{background:x}} aria-label={`${x} 색상`} aria-pressed={value===x} className={value===x?'on':''} onClick={()=>onChange(x)}/>)}</div>;}

function HistoryIcon({redo=false}) {return <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" style={redo?{transform:'scaleX(-1)'}:undefined}><path d="M9 4 4 9l5 5M4 9h10a6 6 0 0 1 0 12"/></svg>;}
function PinchIcon(){return <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M8 13V7a2 2 0 0 1 4 0v5-7a2 2 0 0 1 4 0v7-5a2 2 0 0 1 4 0v8c0 4-2.5 7-7 7h-1c-2 0-3.5-1-4.5-2.5L4 16a2 2 0 0 1 3-2l2 2"/><path d="m3 5 3 2m15-2-3 2"/></svg>;}
const SEARCH_ALIASES={하트:'heart',사랑:'love',별:'star',꽃:'flower',고양이:'cat',강아지:'dog',개:'dog',나비:'butterfly',리본:'ribbon',불:'fire',웃음:'laugh',웃는:'smile',눈물:'cry',선글라스:'sunglasses',안경:'glasses',반짝:'sparkle',해:'sun',달:'moon',구름:'cloud',비:'rain',무지개:'rainbow',음악:'music',카메라:'camera',사진:'camera',케이크:'cake',커피:'coffee',과일:'fruit',체리:'cherry',딸기:'strawberry',축구:'soccer',농구:'basketball',옷:'shirt',신발:'shoe',가방:'bag',왕관:'crown',테이프:'tape',손:'hand',토끼:'rabbit',곰:'bear',토마토:'tomato',피자:'pizza',햄버거:'burger',귀여운:'cute'};
function matchesMaterial(value,query) {const q=query.trim().toLowerCase(),v=value.toLowerCase();return !q||v.includes(q)||!!SEARCH_ALIASES[q]&&v.includes(SEARCH_ALIASES[q]);}
function MaterialSearch({label,value,onChange,placeholder}) {return <div className="rc-material-search"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg><input type="search" className="rc-lab-search-input" aria-label={label} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></div>;}
function MaterialEmpty({title,description}){return <div className="rc-material-empty" role="status"><p>{title}</p>{description&&<span>{description}</span>}</div>;}
function ScrollMore({shown,total,onMore}){const ref=useRef(null),more=useRef(onMore);more.current=onMore;useEffect(()=>{if(shown>=total||!ref.current)return;const observer=new IntersectionObserver(entries=>{if(entries.some(x=>x.isIntersecting)){observer.disconnect();more.current();}},{rootMargin:'80px'});observer.observe(ref.current);return()=>observer.disconnect();},[shown,total]);return shown<total?<div ref={ref} className="rc-scroll-more" aria-hidden="true"/>:null;}
function GiphyPicker({onAdd}) {
 const [query,setQuery]=useState(''),[group,setGroup]=useState('전체'),[limit,setLimit]=useState(60),[results,setResults]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const key=import.meta.env.VITE_GIPHY_API_KEY||sessionStorage.getItem('rc_giphy_key');
 const words={'고양이':'cat','강아지':'dog','하트':'heart','반짝':'sparkle','사랑':'love','웃음':'laugh','춤':'dance','놀람':'surprise','울음':'cry','귀여운':'cute'};
 const q=(words[query.trim()]||query.trim()).toLowerCase();
 const pool=GIPHY_PICKS.filter(x=>(group==='전체'||x.category===group)&&(!q||`${x.label} ${x.category}`.toLowerCase().includes(q)));
 useEffect(()=>{setLimit(60);setResults(null);},[query,group]);
 const search=async()=>{if(!key)return;setBusy(true);setError('');try{const p=new URLSearchParams({api_key:key,limit:'48',rating:'pg-13',lang:'ko',q:query||group});const r=await fetch(`https://api.giphy.com/v1/gifs/search?${p}`);if(!r.ok)throw new Error('검색에 연결하지 못했어요. 공개 픽은 계속 쓸 수 있어요.');setResults((await r.json()).data);}catch(e){setError(e.message);}finally{setBusy(false);}};
 return <div className="rc-giphy-picker"><div className="rc-lab-title"><h3>GIF <small>{GIPHY_PICKS.length}</small></h3><span>Powered by GIPHY</span></div><MaterialSearch label="GIF 찾기" value={query} onChange={setQuery} placeholder="GIF 검색 · 고양이, 하트, dance…"/><div className="rc-gif-categories"><Options values={['전체',...new Set(GIPHY_PICKS.map(x=>x.category))]} value={group} onChange={setGroup}/></div>
 <div className="rc-giphy-results rc-giphy-one-tap">{results?results.map(x=><button key={x.id} aria-label={`${x.title||'GIF'} 넣기`} onClick={()=>onAdd({type:'giphy',giphyId:x.id,label:x.title||'GIPHY',ratio:Number(x.images.original.width)/Number(x.images.original.height),source:x.url})}><img src={x.images.fixed_width?.url||x.images.original.url} alt={x.title||'GIF'} loading="lazy"/></button>):pool.slice(0,limit).map(x=><button key={x.id} aria-label={`${x.label} GIF 넣기`} onClick={()=>onAdd({type:'giphy',giphyId:x.id,label:x.label,source:x.source})}><img src={x.preview} alt={x.label} loading="lazy"/><span>＋</span></button>)}{!results&&<ScrollMore shown={limit} total={pool.length} onMore={()=>setLimit(n=>n+60)}/>}</div>{(results?results.length===0:pool.length===0)&&<MaterialEmpty title="검색 결과가 없어요." description="다른 검색어나 카테고리로 찾아보세요."/>}{key&&<button className="rc-lab-button" disabled={busy} onClick={search}>{busy?'검색 중…':'GIPHY 전체 검색'}</button>}{error&&<p role="alert">{error}</p>}</div>;
}

export default function StoryEditor({initial,owned,collections,onClose,onSave,editingExisting=false}) {
 const [look,setLook]=useState(()=>({...initial,note:initial.note||(editingExisting?initial.title||'':''),items:arrange(initial.items),decorations:normalizeLayers(initial.decorations)})),[mobile,setMobile]=useState(()=>matchMedia('(max-width:650px)').matches),[tool,setTool]=useState(()=>matchMedia('(max-width:650px)').matches?null:'스티커'),[selected,setSelected]=useState(null),[pack,setPack]=useState('오픈모지'),[category,setCategory]=useState('전체'),[filter,setFilter]=useState(''),[stickerLimit,setStickerLimit]=useState(100),[source,setSource]=useState('샘플'),[replacing,setReplacing]=useState(false),[editingText,setEditingText]=useState(null),[color,setColor]=useState('#292824'),[brush,setBrush]=useState('pen'),[width,setWidth]=useState(1),[busy,setBusy]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState(''),[historyState,setHistoryState]=useState([0,0]),[layersOpen,setLayersOpen]=useState(false);
 const originalLook=useRef(look),closeRequestRef=useRef(null);
 const [confirmEdit,setConfirmEdit]=useState(false),[step,setStep]=useState(1),[panelHeight,setPanelHeight]=useState(null);
 const panelDrag=useRef(null);
 const hasChanges=JSON.stringify(look)!==JSON.stringify(originalLook.current);
 const requestClose=()=>{finishText();if(editingExisting&&hasChanges)setConfirmEdit(true);else onClose();};
 closeRequestRef.current=requestClose;
 useEffect(()=>{const mq=matchMedia('(max-width:650px)');const change=()=>setMobile(mq.matches);mq.addEventListener('change',change);return()=>mq.removeEventListener('change',change);},[]);
 useEffect(()=>{if(!mobile)return;const before=document.body.style.overflow;document.body.style.overflow='hidden';const close=e=>{if(e.key==='Escape'&&!confirmEdit)closeRequestRef.current();};window.addEventListener('keydown',close);return()=>{document.body.style.overflow=before;window.removeEventListener('keydown',close);};},[mobile,confirmEdit]);
 const [imageHistory,setImageHistory]=useState([]),[imageFilter,setImageFilter]=useState(''),[itemFilter,setItemFilter]=useState('');
 useEffect(()=>{let active=true;readImageHistory().then(images=>{if(active)setImageHistory(images);}).catch(()=>{});return()=>{active=false;};},[]);
 const recordImages=async images=>{try{setImageHistory(await rememberImages(images));}catch{setError('이미지는 추가됐지만 이 브라우저에 기록을 보관하지 못했어요.');}};
 const lookRef=useRef(look),past=useRef([]),future=useRef([]),editorRef=useRef(null),stageRef=useRef(null);
 lookRef.current=look;
 const syncHistory=()=>setHistoryState([past.current.length,future.current.length]);
 const checkpoint=()=>{past.current=[...past.current.slice(-29),lookRef.current];future.current=[];syncHistory();};
 const commit=change=>{checkpoint();const next=typeof change==='function'?change(lookRef.current):change;lookRef.current=next;setLook(next);};
 const patch=p=>commit(l=>({...l,...p}));
 const undo=redo=>{setEditingText(null);const from=redo?future:past,to=redo?past:future;if(!from.current.length)return;to.current.push(lookRef.current);const next=from.current.pop();lookRef.current=next;setLook(next);setSelected(null);syncHistory();};
 const layers=look.decorations;
 const layerSelected=selected?.startsWith('layer:');
 const signatureSelected=selected==='signature';
 const chosen=layerSelected?layers.find(x=>`layer:${x.id}`===selected):signatureSelected?{id:'signature',type:'signature',text:look.title||'텍스트',name:look.title||'텍스트',size:28,rotation:0}:look.items.find(x=>x.id===selected);
 const textSelected=signatureSelected||(layerSelected&&chosen?.type==='text');
 const updateSelected=p=>signatureSelected?patch({title:p.text??look.title}):commit(l=>({...l,[layerSelected?'decorations':'items']:l[layerSelected?'decorations':'items'].map(x=>x.id===chosen.id?{...x,...p}:x)}));
 const move=(identifier,p,kind)=>{const field=kind==='layer'?'decorations':'items';setLook(l=>{const next={...l,[field]:l[field].map(x=>x.id===identifier?{...x,...p}:x)};lookRef.current=next;return next;});};
 useEffect(()=>{if(editingExisting){setStatus(hasChanges?'수정 중':'');return;}try{writeDraft(look);setStatus('임시 저장됨');}catch{setStatus('큰 이미지는 저장 버튼으로 보관해 주세요');}},[look,editingExisting,hasChanges]);
 useEffect(()=>{const sheet=editorRef.current?.closest('.lb-sheet');if(sheet)sheet.scrollTop=0;editorRef.current?.querySelectorAll('.rc-editor-grid,.rc-editor-controls,.rc-preview').forEach(x=>{x.scrollTop=0;});},[]);
 useEffect(()=>{const panel=editorRef.current?.querySelector('.rc-editor-controls');if(panel)panel.scrollTop=0;},[tool,pack]);
 const addLayers=next=>{if(lookRef.current.decorations.length+next.length>80){setError('장식은 한 스타일에 80개까지 넣을 수 있어요.');return false;}const top=Math.max(20,...lookRef.current.items.map(x=>x.z||0),...lookRef.current.decorations.map(x=>x.z||0));const added=next.map((l,i)=>({id:id(),x:50,y:45,scale:28,size:28,rotation:0,opacity:1,...l,z:top+i+1}));commit(l=>({...l,decorations:[...l.decorations,...added]}));setSelected(`layer:${added.at(-1).id}`);if(mobile)setTool(null);return true;};
 const addLayer=layer=>addLayers([layer]);
 const importFiles=async files=>{setBusy(true);setError('');try{const list=[...files];if(list.length>8)throw new Error('한 번에 이미지는 8개까지 넣어 주세요.');const incoming=await Promise.all(list.map(async(file,i)=>({type:'image',img:await importFile(file),label:file.name||'붙여넣은 이미지',x:40+i*4,y:45+i*3,scale:35})));if(addLayers(incoming))await recordImages(incoming);}catch(e){setError(e.message||'이미지를 가져오지 못했어요.');}finally{setBusy(false);}};

 const paste=e=>{const files=[...e.clipboardData.files];if(files.length){e.preventDefault();importFiles(files);}};
 const finishText=()=>{const key=editingText;if(key&&key!=='signature'){const target=lookRef.current.decorations.find(x=>`layer:${x.id}`===key);if(target&&!target.text.trim()){const next={...lookRef.current,decorations:lookRef.current.decorations.filter(x=>x.id!==target.id)};lookRef.current=next;setLook(next);setSelected(null);}}setEditingText(null);};
 const editText=key=>{if(editingText===key)return;if(editingText)finishText();checkpoint();setSelected(key);setEditingText(key);setTool(null);};
 const startText=()=>{finishText();if(lookRef.current.decorations.length>=80){setError('장식은 한 스타일에 80개까지 넣을 수 있어요.');return;}const key=id();const top=Math.max(20,...lookRef.current.items.map(x=>x.z||0),...lookRef.current.decorations.map(x=>x.z||0));commit(l=>({...l,decorations:[...l.decorations,{id:key,type:'text',text:'',x:50,y:40,size:28,scale:28,font:'sans',bold:true,color:'#292824',rotation:0,z:top+1}]}));setSelected(`layer:${key}`);setEditingText(`layer:${key}`);setTool(null);};
 const typeText=(key,value)=>{const next=key==='signature'?{...lookRef.current,title:value}:{...lookRef.current,decorations:lookRef.current.decorations.map(x=>`layer:${x.id}`===key?{...x,text:value}:x)};lookRef.current=next;setLook(next);};
 const selectElement=key=>{if(editingText&&key!==editingText)finishText();setSelected(key);if(mobile)setTool(null);};

 const addItem=it=>{if(replacing&&chosen&&!layerSelected&&!look.items.some(x=>x.id===it.id)){commit(l=>({...l,items:l.items.map(x=>x.id===chosen.id?{...it,x:x.x,y:x.y,scale:x.scale,rotation:x.rotation,z:x.z}:x)}));setSelected(it.id);setReplacing(false);return;}if(look.items.length>=12){setError('옷은 12개까지 담을 수 있어요.');return;}if(look.items.some(x=>x.id===it.id)){setSelected(it.id);return;}commit(l=>({...l,items:arrange([...l.items,it])}));setSelected(it.id);};
 const remove=()=>{setEditingText(null);if(signatureSelected)patch({title:''});else commit(l=>({...l,[layerSelected?'decorations':'items']:l[layerSelected?'decorations':'items'].filter(x=>x.id!==chosen.id)}));setSelected(null);};
 const download=async()=>{setError('');try{await exportImage(look);}catch(e){setError(e.message||'이미지를 내보내지 못했어요.');}};
 const save=async()=>{finishText();setSaving(true);setError('');try{await onSave({...lookRef.current,title:lookRef.current.note.trim().slice(0,80)||'나의 피드'});if(!editingExisting)clearDraft();onClose();}catch(e){setError(e.message);}finally{setSaving(false);}};
 useEffect(()=>setStickerLimit(100),[pack,category,filter]);
 const stickers=CUTOUTS.filter(x=>(category==='전체'||x.category===category)&&matchesMaterial(x.label,filter));
 const openmoji=OPENMOJI.filter(x=>(category==='전체'||x.category===category)&&matchesMaterial(x.label+' '+x.tags+' '+x.category,filter));
 const emojis=Object.entries(EMOJI_PACKS).filter(([key])=>category==='전체'||key===category).flatMap(([name,values])=>values.map(value=>({value,name}))).filter(x=>matchesMaterial(x.name+' '+x.value+' '+(OPENMOJI.find(m=>m.label.startsWith(x.value+' '))?.tags||''),filter));
 const allSourceItems=source==='내 아이템'?owned.map(thumb):source==='만들기 재료'?collections.filter(x=>x.type==='item').map(x=>({...x.item,kind:'inspiration'})):SAMPLE_ITEMS;
 const sourceItems=allSourceItems.filter(x=>`${x.name} ${x.category}`.toLowerCase().includes(itemFilter.trim().toLowerCase()));
 const next=()=>{finishText();setSelected(null);setTool(null);setError('');setStep(2);};
 const resizePanel=value=>{const h=window.visualViewport?.height||window.innerHeight;const header=editorRef.current?.querySelector('.rc-lab-header')?.getBoundingClientRect().height||64,toolbar=editorRef.current?.querySelector('.rc-lab-toolbar')?.getBoundingClientRect().height||86;const max=Math.max(80,Math.min(h*.56,h-header-toolbar-172));setPanelHeight(Math.max(Math.min(h*.4,max),Math.min(max,value)));};
 const panelHandle=mobile?<button type="button" className="rc-panel-resize" aria-label="옵션 메뉴 높이 조절" title="위로 끌어 메뉴 확대" onPointerDown={e=>{e.preventDefault();e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);panelDrag.current={id:e.pointerId,y:e.clientY,height:e.currentTarget.parentElement.getBoundingClientRect().height};}} onPointerMove={e=>{const d=panelDrag.current;if(d&&d.id===e.pointerId)resizePanel(d.height+d.y-e.clientY);}} onPointerUp={()=>{panelDrag.current=null;}} onPointerCancel={()=>{panelDrag.current=null;}} onKeyDown={e=>{if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();resizePanel((panelHeight||window.innerHeight*.4)+(e.key==='ArrowUp'?24:-24));}}}><span/></button>:null;
 const content=step===2?<section className={`rc-editor rc-story rc-publish ${mobile?'rc-story-mobile':'rc-story-desktop'}`} role="dialog" aria-modal="true" aria-label="피드 게시하기"><header className="rc-publish-header"><button aria-label="이미지 편집으로 돌아가기" onClick={()=>setStep(1)}><span aria-hidden="true">←</span> 이전</button><h2>{editingExisting?'게시글 수정':'피드 게시하기'}</h2><Btn size="sm" disabled={saving} onClick={()=>editingExisting?setConfirmEdit(true):save()} style={{background:'#BF603D',color:'#fff',border:'none',padding:'0 16px',height:34,fontSize:12}}>{saving?'저장 중…':editingExisting?'수정 완료':'게시'}</Btn></header><div className="rc-publish-content"><div className="rc-publish-preview"><StyleCanvas look={look} showCredits={false}/></div><div className="rc-publish-fields"><label htmlFor="rc-feed-caption">글 작성</label><textarea id="rc-feed-caption" aria-label="피드 글 작성" placeholder="이 피드에 담고 싶은 이야기를 적어 주세요." value={look.note||''} maxLength={600} onChange={e=>patch({note:e.target.value})}/><small className="rc-caption-count">{(look.note||'').length}/600</small><fieldset className="rc-publish-privacy"><legend>공개 범위</legend><div role="group" aria-label="피드 공개 범위">{[['public','전체 공개'],['link','링크 공개'],['private','나만 보기']].map(([value,label])=><button key={value} type="button" aria-pressed={look.privacy===value} onClick={()=>patch({privacy:value})}>{label}</button>)}</div></fieldset></div></div>{error&&<p className="rc-error" role="alert">{error}</p>}</section>:<section ref={editorRef} className={`rc-editor rc-story ${mobile?'rc-story-mobile':'rc-story-desktop'} rc-step-1 ${tool?'rc-material-open':''}`} style={panelHeight?{'--rc-requested-panel-height':`${panelHeight}px`}:undefined} role="dialog" aria-modal="true" aria-label="스타일 만들기" onPaste={paste} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(e.dataTransfer.files.length)importFiles(e.dataTransfer.files);}}>
 <header className="rc-lab-header">{mobile&&<button className="rc-lab-close" aria-label="편집 닫기" onClick={requestClose}><Icon name="x" size={20}/></button>}<div className="rc-editor-brand">{mobile?'':<span>STYLE LAB</span>}<h2 title={status}>{editingExisting?'수정하기':'만들기'}</h2></div><div className="rc-top-actions"><button aria-label="되돌리기" title="되돌리기" disabled={!historyState[0]} onClick={()=>undo(false)}><HistoryIcon/></button><button aria-label="다시 하기" title="다시 하기" disabled={!historyState[1]} onClick={()=>undo(true)}><HistoryIcon redo/></button>{!mobile&&<button aria-label="편집 닫기" title="편집 닫기" onClick={requestClose}><Icon name="x" size={22}/></button>}{mobile&&<button className="rc-top-done" disabled={saving||(!look.items.length&&!layers.length)||(editingExisting&&!hasChanges)} onClick={next}>{saving?(editingExisting?'저장 중…':'게시 중…'):'다음'}</button>}</div></header>
 <div className="rc-editor-grid"><div className="rc-preview"><div className="rc-lab-canvas-wrap" onPointerDown={e=>{if(e.target===e.currentTarget){finishText();setSelected(null);setReplacing(false);}}}>{!mobile&&<button className="rc-canvas-elements" aria-expanded={layersOpen} onClick={()=>{setLayersOpen(!layersOpen);setTool(tool==='펜'?'스티커':tool);}}>꾸미기 요소 {look.items.length+layers.length}</button>}<StyleCanvas look={look} editing selected={selected} onSelect={selectElement} editingText={editingText} onTextChange={typeText} onTextEdit={editText} onTextDone={finishText} onEmptyPointerDown={()=>{finishText();setSelected(null);setReplacing(false);}} onGesture={checkpoint} onMove={move} stageRef={stageRef} pen={tool==='펜'?{color,width,brush}:null} onStroke={addLayer}/></div>
 {textSelected&&chosen&&<div className="rc-text-tools" aria-label="선택한 텍스트 꾸미기">{panelHandle}<div className="rc-text-tools-row">{!signatureSelected&&<><button aria-label="굵게" aria-pressed={chosen.bold??chosen.font==='bold'} onClick={()=>updateSelected({bold:!(chosen.bold??chosen.font==='bold')})}><b>B</b></button><button aria-label="기울임" aria-pressed={!!chosen.italic} onClick={()=>updateSelected({italic:!chosen.italic})}><i>I</i></button><select aria-label="텍스트 글꼴" value={chosen.font==='bold'?'sans':chosen.font||'sans'} onChange={e=>updateSelected({font:e.target.value,bold:chosen.bold??chosen.font==='bold'})}>{['sans','serif','mono','hand'].map(x=><option key={x} value={x}>{({sans:'기본',serif:'세리프',mono:'타자기',hand:'손글씨'})[x]}</option>)}</select><button aria-label="텍스트 배경" aria-pressed={chosen.textStyle==='label'} onClick={()=>updateSelected({textStyle:chosen.textStyle==='label'?'plain':'label',bg:'#ffffff'})}>▣</button></>}<button aria-label="텍스트 수정" onClick={()=>editText(selected)}><Icon name="pencil" size={18}/></button><button aria-label="텍스트 삭제" onClick={remove}><Icon name="trash" size={18}/></button><button className="rc-text-done" onClick={()=>{finishText();setSelected(null);}}>완료</button></div>{!signatureSelected&&<div className="rc-text-colors">{INKS.map(value=><button key={value} aria-label={`${value} 텍스트 색상`} aria-pressed={(chosen.color||'#292824')===value} style={{background:value}} onClick={()=>updateSelected({color:value})}/>)}</div>}{signatureSelected&&<input autoFocus aria-label="캔버스 제목 입력" value={look.title} maxLength={80} onChange={e=>typeText('signature',e.target.value)}/>}</div>}
 {<>
 {chosen&&!textSelected&&tool!=='펜'&&(!mobile||!tool)&&<div className="rc-lab-selection"><div className="rc-between"><span>{chosen.name||chosen.label||chosen.text||'펜 낙서'}</span>{mobile&&<small className="rc-gesture-hint"><PinchIcon/><span>두 손가락으로 크기·회전</span></small>}<button aria-label="선택 해제" onClick={()=>setSelected(null)}>×</button></div>
 {!signatureSelected&&<><label>{layerSelected&&chosen.type==='text'?'글자 크기':'크기'}<input aria-label="선택한 요소 크기" type="range" min={layerSelected&&chosen.type==='text'?12:8} max={layerSelected&&chosen.type==='text'?70:110} value={layerSelected&&chosen.type==='text'?chosen.size:chosen.scale} onChange={e=>updateSelected({[layerSelected&&chosen.type==='text'?'size':'scale']:+e.target.value})}/></label><label>회전<input aria-label="선택한 요소 회전" type="range" min="-180" max="180" value={chosen.rotation||0} onChange={e=>updateSelected({rotation:+e.target.value})}/></label></>}{layerSelected&&<label>투명도<input aria-label="선택한 요소 투명도" type="range" min=".1" max="1" step=".05" value={chosen.opacity??1} onChange={e=>updateSelected({opacity:+e.target.value})}/></label>}
 <div className="rc-lab-layer-actions">{layerSelected&&<button onClick={()=>addLayer({...chosen,id:id(),x:Math.min(95,chosen.x+4),y:Math.min(95,chosen.y+4)})}>복제</button>}<button onClick={remove}>삭제</button></div>
 {layerSelected&&<><label className="rc-lab-field">움직임<select aria-label="요소 움직임" value={chosen.motion||'none'} onChange={e=>updateSelected({motion:e.target.value})}><option value="none">없음</option><option value="float">둥실</option><option value="pulse">두근</option><option value="wiggle">흔들</option></select></label>{chosen.type==='text'&&<Swatches value={chosen.color} onChange={color=>updateSelected({color})}/>}</>}
 </div>}
 {layersOpen&&<div className="rc-lab-layers">{[...layers.map(x=>({...x,key:`layer:${x.id}`})),...look.items.map(x=>({...x,key:x.id}))].sort((a,b)=>(b.z||0)-(a.z||0)).map(x=><button key={x.key} className={selected===x.key?'on':''} onClick={()=>setSelected(x.key)}>{x.name||x.text||x.label||'펜 낙서'}</button>)}</div>}</>}
 </div><div className={`rc-editor-controls ${tool?'open':''}`}>{<><div className="rc-lab-toolbar" role="tablist" aria-label="스타일 꾸미기 도구">{TOOLS.map(x=><button role="tab" aria-selected={tool===x||(x==='텍스트'&&textSelected)} className={tool===x||(x==='텍스트'&&textSelected)?'on':''} key={x} onClick={()=>{if(x==='텍스트'){startText();return;}finishText();setTool(tool===x&&mobile?null:x);setSelected(null);setError('');setReplacing(false);}}><span className="rc-tool-symbol">{({스티커:'☺',펜:'✎',텍스트:'Aa',이미지:'▧',GIF:'GIF',옷장:'♧',배경:'◐'})[x]}</span><span>{x}</span></button>)}</div><div className={`rc-lab-panel${!tool?' rc-panel-empty':''}`}>{panelHandle}{mobile&&tool&&<button className="rc-material-close" aria-label="재료 닫기" onClick={()=>setTool(null)}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="m6 9 6 6 6-6"/></svg></button>}
 {tool==='스티커'&&<><div className="rc-lab-title"><h3>스티커</h3><span>{84+144+OPENMOJI.length} PICKS</span></div><Options values={['오픈모지','무빙','콜라주','이모지']} value={pack} onChange={x=>{setPack(x);setCategory('전체');setFilter('');}}/><MaterialSearch label="스티커 찾기" placeholder="스티커 검색 · 별, 테이프, 꽃…" value={filter} onChange={setFilter}/><div className="rc-lab-category"><Options values={['전체',...(pack==='콜라주'?[...new Set(CUTOUTS.map(x=>x.category))]:['오픈모지','무빙'].includes(pack)?[...new Set(OPENMOJI.map(x=>x.category))]:Object.keys(EMOJI_PACKS))]} value={category} onChange={setCategory}/></div><div className="rc-sticker-grid">{pack!=='이모지'?(['오픈모지','무빙'].includes(pack)?openmoji:stickers).slice(0,stickerLimit).map(x=><button key={x.id} aria-label={`${x.label} 스티커 넣기`} onClick={()=>addLayer({type:'image',img:x.img,label:x.label,source:x.source,motion:pack==='무빙'?['float','pulse','wiggle'][OPENMOJI.indexOf(x)%3]:'none',scale:x.category==='테이프'?35:25})}><img className={pack==='무빙'?'rc-sticker-bounce':undefined} src={x.img} alt={x.label} loading="lazy"/></button>):emojis.map(x=><button key={x.value} aria-label={`${x.value} 이모지 넣기`} onClick={()=>addLayer({type:'text',text:x.value,size:48})}>{x.value}</button>)}{pack!=='이모지'&&<ScrollMore shown={stickerLimit} total={['오픈모지','무빙'].includes(pack)?openmoji.length:stickers.length} onMore={()=>setStickerLimit(n=>n+100)}/>}</div>{!(pack==='콜라주'?stickers.length:['오픈모지','무빙'].includes(pack)?openmoji.length:emojis.length)&&<MaterialEmpty title="검색 결과가 없어요." description="다른 검색어나 카테고리로 찾아보세요."/>}{['오픈모지','무빙'].includes(pack)&&<p className="rc-lab-help"><a href="https://openmoji.org/" target="_blank" rel="noreferrer">OpenMoji</a> 원본 이미지 · <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noreferrer">CC BY-SA 4.0</a></p>}</>}
 {tool==='펜'&&<><div className="rc-lab-title"><h3>펜</h3><span>DRAW ON THE LOOK</span></div><p className="rc-lab-help">왼쪽 코디 위에 바로 그려요. 모바일에서는 위 캔버스에 손가락으로 그려요.</p><Options values={['pen','marker','highlighter','dotted']} value={brush} onChange={x=>{setBrush(x);setWidth(x==='marker'?3:x==='highlighter'?6:1);}}/><p className="rc-lab-help">펜 · 마커 · 형광펜 · 점선</p><Swatches value={color} onChange={setColor}/><label className="rc-lab-field">굵기<input aria-label="펜 굵기" type="range" min=".4" max="8" step=".2" value={width} onChange={e=>setWidth(+e.target.value)}/></label><button className="rc-lab-button" onClick={()=>setTool('스티커')}>그리기 끝내기</button></>}

 {tool==='이미지'&&<><div className="rc-lab-title"><h3>이미지</h3></div><label className="rc-lab-upload" aria-busy={busy}>이미지 추가<input disabled={busy} aria-label="콜라주 이미지 업로드" type="file" accept="image/png,image/jpeg,image/webp,image/avif,image/gif" multiple onChange={e=>{if(e.target.files.length)importFiles(e.target.files);e.target.value='';}}/></label><h4>내가 추가한 이미지</h4><MaterialSearch label="내 이미지 찾기" value={imageFilter} onChange={setImageFilter} placeholder="파일 이름으로 검색"/><div className="rc-photo-picks">{imageHistory.filter(x=>x.label.toLowerCase().includes(imageFilter.trim().toLowerCase())).map(x=><button key={x.img} aria-label={`${x.label} 다시 넣기`} onClick={()=>addLayer({...x,scale:38})}><img src={x.img} alt={x.label} loading="lazy"/></button>)}</div>{!imageHistory.length&&<MaterialEmpty title="아직 추가한 이미지가 없어요."/>}{imageHistory.length>0&&!imageHistory.some(x=>x.label.toLowerCase().includes(imageFilter.trim().toLowerCase()))&&<MaterialEmpty title="검색 결과가 없어요." description="다른 검색어로 찾아보세요."/>}</>}
 {tool==='GIF'&&<GiphyPicker onAdd={addLayer}/>}
 {tool==='옷장'&&<><div className="rc-lab-title"><h3>옷장</h3><span>STYLE THE SAME CLOSET</span></div><label className="rc-product-info-option"><input type="checkbox" checked={look.items.length>0&&look.items.every(x=>x.showInfo)} onChange={e=>{const showInfo=e.target.checked;commit(l=>({...l,items:l.items.map(x=>({...x,showInfo}))}));}}/>브랜드·가격 표시</label><Options values={['샘플','내 아이템','만들기 재료']} value={source} onChange={setSource}/><MaterialSearch label="옷 찾기" value={itemFilter} onChange={setItemFilter} placeholder="옷 검색 · 이름, 종류"/><div className="rc-item-picker">{sourceItems.map(it=><button key={it.id} className={'rc-item'+(look.items.some(x=>x.id===it.id)?' picked':'')} aria-label={`${it.name} 담기`} onClick={()=>addItem(it)}><img src={it.img} alt=""/><span>{it.name}</span></button>)}</div>{!sourceItems.length&&<MaterialEmpty title={allSourceItems.length?'검색 결과가 없어요.':source==='내 아이템'?'아직 등록한 아이템이 없어요.':source==='만들기 재료'?'아직 만들기 재료가 없어요.':'아직 사용할 수 있는 샘플이 없어요.'} description={allSourceItems.length?'다른 검색어로 찾아보세요.':source==='만들기 재료'?'피드 아이템과 공개 옷에서 담은 재료가 여기에 모여요.':undefined}/>}{chosen&&!layerSelected&&<button className="rc-lab-button" onClick={()=>setReplacing(!replacing)}>{replacing?'바꿀 옷을 골라 주세요':'선택한 옷 바꾸기'}</button>}</>}
 {tool==='배경'&&<><div className="rc-lab-title"><h3>배경</h3><span>COLOR THE MOMENT</span></div><div className="rc-background-grid">{Object.entries(BACKGROUNDS).map(([key,bg])=><button key={key} style={{background:bg,color:key==='ink'?'#fff':'#292824'}} aria-pressed={look.background===key} onClick={()=>patch({background:key})}>{({ivory:'아이보리',paper:'종이',sage:'세이지',sand:'샌드',ink:'차콜',lime:'라임',pink:'핑크',blue:'블루',lavender:'라벤더'})[key]}</button>)}</div></>}
 </div></>}
 </div></div>{error&&<p className="rc-error" role="alert">{error}</p>}<footer className="rc-editor-footer"><a className="rc-lab-link rc-sticker-source" href="/asset-credits.html" target="_blank" rel="noreferrer">스티커 출처</a><button className="rc-lab-link" onClick={download}>PNG 내보내기</button><Btn disabled={saving||(!look.items.length&&!layers.length)||(editingExisting&&!hasChanges)} onClick={next}>{saving?(editingExisting?'저장 중…':'게시 중…'):'다음'}</Btn></footer>
 </section>;
 return createPortal(<>{mobile?<div className="rc-mobile-editor-shell">{content}</div>:<BottomSheet open centered onClose={requestClose} desktopMaxW={1120} maxW={1120} zIndex={150} dismissOnScrim={true}>{content}</BottomSheet>}{confirmEdit&&<StudioSheet open centered title="게시글을 수정할까요?" desktopMaxW={400} zIndex={180} dismissOnScrim onClose={()=>{if(!saving)setConfirmEdit(false);}}><div className="rc-edit-confirm"><p>변경 취소를 누르면 수정 전 게시글로 돌아가요.</p>{error&&<p className="rc-error" role="alert">{error}</p>}<div><Btn variant="soft" disabled={saving} onClick={()=>{setConfirmEdit(false);onClose();}}>변경 취소</Btn><Btn disabled={saving} onClick={save}>{saving?'저장 중…':'수정 완료'}</Btn></div></div></StudioSheet>}</>,document.body);
}
